server.port=9000
server.servlet.context-path=/workintech

management.endpoints.web.exposure.include=info,health,mappings
management.info.env.enabled=true

info.app.name=zoo
info.app.description=Zoo REST API
info.app.version=0.0.1-SNAPSHOT

info.name=zoo
info.description=Zoo REST API
info.version=0.0.1-SNAPSHOT